els-ASAP auto commit file/tag virt-what-1.18-4.el7.src.rpm

diff --git a/src/virt-what.in b/src/virt-what.in
--- a/src/virt-what.in
+++ b/src/virt-what.in
@@ -1,6 +1,6 @@
-#!/bin/bash -
+#!/bin/sh -
 # @configure_input@
-# Copyright (C) 2008-2011 Red Hat Inc.
+# Copyright (C) 2008-2015 Red Hat Inc.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,27 +18,32 @@
 
 # 'virt-what' tries to detect the type of virtualization being
 # used (or none at all if we're running on bare-metal).  It prints
-# out one of more lines each being a 'fact' about the virtualization.
+# out one or more lines each being a 'fact' about the virtualization.
 #
 # Please see also the manual page virt-what(1).
 # This script should be run as root.
 #
 # The following resources were useful in writing this script:
-# . http://www.dmo.ca/blog/20080530151107
+# . http://dmo.ca/blog/detecting-virtualization-on-linux/
 
 # Do not allow unset variables, and set defaults.
 set -u
 root=''
 skip_qemu_kvm=false
+skip_lkvm=false
 
 VERSION="@VERSION@"
 
-function fail {
+have_cpuinfo () {
+    test -e "${root}/proc/cpuinfo"
+}
+
+fail () {
     echo "virt-what: $1" >&2
     exit 1
 }
 
-function usage {
+usage () {
     echo "virt-what [options]"
     echo "Options:"
     echo "  --help          Display this help"
@@ -47,36 +52,41 @@ function usage {
 }
 
 # Handle the command line arguments, if any.
-
-TEMP=$(getopt -o v --long help --long version --long test-root: -n 'virt-what' -- "$@")
-if [ $? != 0 ]; then exit 1; fi
-eval set -- "$TEMP"
-
-while true; do
+while test $# -gt 0; do
     case "$1" in
-	--help) usage ;;
-        --test-root)
+        --help) usage ;;
+        --test-root=*)
             # Deliberately undocumented: used for 'make check'.
-            root="$2"
-            shift 2
+            root=$(echo "$1" | sed 's/.*=//')
+            shift 1
+            test -z "$root" && fail "--test-root option requires a value"
             ;;
-	-v|--version) echo "$VERSION"; exit 0 ;;
-	--) shift; break ;;
-	*) fail "internal error ($1)" ;;
+        -v|--version) echo "$VERSION"; exit 0 ;;
+        --) shift; break ;;
+        *) fail "unrecognized option '$1'";;
     esac
 done
+test $# -gt 0 && fail "extra operand '$1'"
 
 # Add /sbin and /usr/sbin to the path so we can find system
-# binaries like dmicode.
+# binaries like dmidecode.
 # Add /usr/libexec to the path so we can find the helper binary.
 prefix=@prefix@
 exec_prefix=@exec_prefix@
 PATH="${root}@libexecdir@:${root}/sbin:${root}/usr/sbin:${PATH}"
+export PATH
 
 # Check we're running as root.
+EFFUID=$(id -u) || fail "failed to get current user id"
 
-if [ "x$root" = "x" ] && [ "$EUID" -ne 0 ]; then
+if [ "x$root" = "x" ] && [ "$EFFUID" -ne 0 ]; then
     fail "this script must be run as root"
+fi
+
+# Try to locate the CPU-ID helper program
+CPUID_HELPER=$(which virt-what-cpuid-helper 2>/dev/null)
+if [ -z "$CPUID_HELPER" ] ; then
+    fail "virt-what-cpuid-helper program not found in \$PATH"
 fi
 
 # Many fullvirt hypervisors give an indication through CPUID.  Use the
@@ -85,16 +95,16 @@ fi
 cpuid=$(virt-what-cpuid-helper)
 
 # Check for various products in the BIOS information.
-# Note that dmidecode doesn't exist on non-PC architectures.  On these,
-# this will return an error which is ignored (error message redirected
-# into $dmi variable).
+# Note that dmidecode doesn't exist on all architectures.  On the ones
+# it does not, then this will return an error, which is ignored (error
+# message redirected into the $dmi variable).
 
 dmi=$(LANG=C dmidecode 2>&1)
 
 # Architecture.
 # Note for the purpose of testing, we only call uname with -p option.
 
-arch=$(uname -p)
+arch=$(uname -p | sed -e 's/i.86/i386/' | sed -e 's/arm.*/arm/')
 
 # Check for VMware.
 # cpuid check added by Chetan Loke.
@@ -125,6 +135,13 @@ if echo "$dmi" | grep -q 'Manufacturer: innotek GmbH'; then
     echo virtualbox
 fi
 
+# Check for bhyve.
+if [ "$cpuid" = "bhyve bhyve " ]; then
+  echo bhyve
+elif echo "$dmi" | grep -q "Vendor: BHYVE"; then
+  echo bhyve
+fi
+
 # Check for OpenVZ / Virtuozzo.
 # Added by Evgeniy Sokolov.
 # /proc/vz - always exists if OpenVZ kernel is running (inside and outside
@@ -145,18 +162,25 @@ if [ -e "${root}/proc/1/environ" ] &&
 fi
 
 # Check for Linux-VServer
-if cat "${root}/proc/self/status" | grep -q "VxID: [0-9]*"; then
+if test -e "${root}/proc/self/status" \
+   && cat "${root}/proc/self/status" | grep -q "VxID: [0-9]*"; then
     echo linux_vserver
+    if grep -q "VxID: 0$" "${root}/proc/self/status"; then
+        echo linux_vserver-host
+    else
+        echo linux_vserver-guest
+    fi
 fi
 
 # Check for UML.
 # Added by Laurent Léonard.
-if grep -q 'UML' "${root}/proc/cpuinfo"; then
+if have_cpuinfo && grep -q 'UML' "${root}/proc/cpuinfo"; then
     echo uml
 fi
 
 # Check for IBM PowerVM Lx86 Linux/x86 emulator.
-if grep -q '^vendor_id.*PowerVM Lx86' "${root}/proc/cpuinfo"; then
+if have_cpuinfo && grep -q '^vendor_id.*PowerVM Lx86' "${root}/proc/cpuinfo"
+then
     echo powervm_lx86
 fi
 
@@ -167,10 +191,12 @@ if echo "$dmi" | grep -q 'Manufacturer.*HITACHI' &&
 fi
 
 # Check for IBM SystemZ.
-if grep -q '^vendor_id.*IBM/S390' "${root}/proc/cpuinfo"; then
+if have_cpuinfo && grep -q '^vendor_id.*IBM/S390' "${root}/proc/cpuinfo"; then
     echo ibm_systemz
     if [ -f "${root}/proc/sysinfo" ]; then
-        if grep -q 'VM.*Control Program.*z/VM' "${root}/proc/sysinfo"; then
+        if grep -q 'VM.*Control Program.*KVM/Linux' "${root}/proc/sysinfo"; then
+            echo ibm_systemz-kvm
+        elif grep -q 'VM.*Control Program.*z/VM' "${root}/proc/sysinfo"; then
             echo ibm_systemz-zvm
         elif grep -q '^LPAR' "${root}/proc/sysinfo"; then
             echo ibm_systemz-lpar
@@ -187,25 +213,45 @@ if echo "$dmi" | grep -q 'Vendor: Parallels'; then
     skip_qemu_kvm=true
 fi
 
+# Check for oVirt/RHEV.
+if echo "$dmi" | grep -q 'Manufacturer: oVirt'; then
+    echo ovirt
+fi
+if echo "$dmi" | grep -q 'Product Name: RHEV Hypervisor'; then
+    echo rhev
+fi
+
 # Check for Xen.
 
 if [ "$cpuid" = "XenVMMXenVMM" ]; then
     echo xen; echo xen-hvm
+    # Check for AWS
+    if echo "$dmi" | grep -q 'Version: [0-9]\.[0-9]\.amazon'; then
+        echo aws
+    fi
     skip_qemu_kvm=true
-elif [ -f "${root}/proc/xen/capabilities" ]; then
+elif [ -d "${root}/proc/xen" ]; then
     echo xen
-    if grep -q "control_d" "${root}/proc/xen/capabilities"; then
+    if grep -q "control_d" "${root}/proc/xen/capabilities" 2>/dev/null; then
         echo xen-dom0
     else
         echo xen-domU
     fi
     skip_qemu_kvm=true
+    skip_lkvm=true
 elif [ -f "${root}/sys/hypervisor/type" ] &&
     grep -q "xen" "${root}/sys/hypervisor/type"; then
     # Ordinary kernel with pv_ops.  There does not seem to be
     # enough information at present to tell whether this is dom0
     # or domU.  XXX
     echo xen
+elif [ "$arch" = "arm" ] || [ "$arch" = "aarch64" ]; then
+    if [ -d "${root}/proc/device-tree/hypervisor" ] &&
+        grep -q "xen" "${root}/proc/device-tree/hypervisor/compatible"; then
+        echo xen
+        skip_qemu_kvm=true
+        skip_lkvm=true
+    fi
 elif [ "$arch" = "ia64" ]; then
     if [ -d "${root}/sys/bus/xen" -a ! -d "${root}/sys/bus/xen-backend" ]; then
         # PV-on-HVM drivers installed in a Xen guest.
@@ -232,14 +278,103 @@ fi
 
 if ! "$skip_qemu_kvm"; then
     if [ "$cpuid" = "KVMKVMKVM" ]; then
-	echo kvm
+        echo kvm
+    elif [ "$cpuid" = "TCGTCGTCGTCG" ]; then
+        echo qemu
+        skip_lkvm=true
+    elif echo "$dmi" | grep -q 'Product Name: KVM'; then
+        echo kvm
+        skip_lkvm=true
+    elif echo "$dmi" | grep -q 'Manufacturer: QEMU'; then
+        # The test for KVM above failed, so now we know we're
+        # not using KVM acceleration.
+        echo qemu
+        skip_lkvm=true
+    elif [ "$arch" = "arm" ] || [ "$arch" = "aarch64" ]; then
+        if [ -d "${root}/proc/device-tree" ] &&
+            ls "${root}/proc/device-tree" | grep -q "fw-cfg"; then
+            # We don't have enough information to determine if we're
+            # using KVM acceleration or not.
+            echo qemu
+            skip_lkvm=true
+        fi
+    elif [ -d ${root}/proc/device-tree/hypervisor ] &&
+         grep -q "linux,kvm" /proc/device-tree/hypervisor/compatible; then
+        # We are running as a spapr KVM guest on ppc64
+        echo kvm
+        skip_lkvm=true
     else
-        # XXX This is known to fail for qemu with the explicit -cpu
+        # This is known to fail for qemu with the explicit -cpu
         # option, since /proc/cpuinfo will not contain the QEMU
-        # string.  The long term fix for this would be to export
-        # another CPUID leaf for non-accelerated qemu.
+        # string. QEMU 2.10 added a new CPUID leaf, so this
+        # problem only triggered for older QEMU
         if grep -q 'QEMU' "${root}/proc/cpuinfo"; then
-	    echo qemu
-	fi
+            echo qemu
+        fi
+    fi
+fi
+
+if ! "$skip_lkvm"; then
+    if [ "$cpuid" = "LKVMLKVMLKVM" ]; then
+        echo lkvm
+    elif [ "$arch" = "arm" ] || [ "$arch" = "aarch64" ]; then
+        if [ -d "${root}/proc/device-tree" ] &&
+            grep -q "dummy-virt" "${root}/proc/device-tree/compatible"; then
+            echo lkvm
+        fi
+    fi
+fi
+
+# Check for Docker.
+if [ -f "${root}/.dockerinit" ]; then
+    echo docker
+fi
+
+# Check ppc64 lpar, kvm or powerkvm
+
+# example /proc/cpuinfo line indicating 'not baremetal'
+# platform  : pSeries
+#
+# example /proc/ppc64/lparcfg systemtype line
+# system_type=IBM pSeries (emulated by qemu)
+
+if [ "$arch" = "ppc64" ]; then
+    if have_cpuinfo && grep -q 'platform.**pSeries' "${root}/proc/cpuinfo"; then
+        if grep -q 'model.*emulated by qemu' "${root}/proc/cpuinfo"; then
+                echo ibm_power-kvm
+        else
+            # Assume LPAR, now detect shared or dedicated
+            if grep -q 'shared_processor_mode=1' "${root}/proc/ppc64/lparcfg"; then
+                echo ibm_power-lpar_shared
+            else
+                echo ibm_power-lpar_dedicated
+            fi
+        # detect powerkvm?
+        fi
+    fi
+fi
+
+# Check for OpenBSD/VMM
+if [ "$cpuid" = "OpenBSDVMM58" ]; then
+        echo vmm
+fi
+
+# Check for LDoms
+if [[ "$arch" == sparc* && -e ${root}/dev/mdesc ]]; then
+    echo ldoms
+    if [[ -d ${root}/sys/class/vlds/ctrl && \
+             -d ${root}/sys/class/vlds/sp ]]; then
+        echo ldoms-control
+    else
+        echo ldoms-guest
+    fi
+    MDPROP="${root}/usr/lib/ldoms/mdprop.py"
+    if [[ -x ${MDPROP} ]]; then
+        if [[ -n $($MDPROP -v iodevice device-type=pciex) ]]; then
+            echo ldoms-root
+            echo ldoms-io
+        elif [[ -n $($MDPROP -v iov-device vf-id=0) ]]; then
+            echo ldoms-io
+        fi
     fi
 fi
